"""Initial schema

Revision ID: c170d3e265f0
Revises: 
Create Date: 2025-06-14 18:20:54.018747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c170d3e265f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('contractor', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('contractor', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('machines', sa.Text(), nullable=True),
    sa.Column('required_date', sa.String(), nullable=True),
    sa.Column('completion_date', sa.String(), nullable=True),
    sa.Column('checklist_no_missing_screws', sa.Boolean(), nullable=True),
    sa.Column('checklist_software_updated', sa.Boolean(), nullable=True),
    sa.Column('checklist_tested', sa.Boolean(), nullable=True),
    sa.Column('checklist_approved_by_management', sa.Boolean(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('status_timestamp', sa.String(), nullable=True),
    sa.Column('contractor_status', sa.String(), nullable=True),
    sa.Column('onsite_time', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('work_required', sa.Text(), nullable=True),
    sa.Column('work_performed', sa.Text(), nullable=True),
    sa.Column('travel_time', sa.String(), nullable=True),
    sa.Column('labour_time', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('customer_address', sa.String(), nullable=True),
    sa.Column('note_count', sa.Integer(), nullable=True),
    sa.Column('assigned_contractor', sa.Integer(), nullable=True),
    sa.Column('assigned_tech', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_contractor'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_tech'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('users')
    op.drop_table('machines')
    # ### end Alembic commands ###
